POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "terra",
    "password": "password123admin"
}

GET http://localhost:3000/books
Content-Type: application/json
Authorization: Bearer TOKEN

POST http://localhost:3000/books
Content-Type: application/json
Authorization: Bearer TOKEN

{
    "author": "Rosa",
    "country": "Indonesia",
    "language": "Bahasa Indonesia",
    "pages": 201,
    "title": "Judul Buku",
    "year": 2021
}